using System;
using System.Reflection;
using System.Runtime.CompilerServices;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.832
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: CLSCompliantAttribute(true)]
[assembly: AssemblyTitleAttribute("NHibernate.Caches.Prevalence")]
[assembly: AssemblyDescriptionAttribute("Cache provider for NHibernate 1.2.1.GA using Bamboo.Prevalence engine.")]
[assembly: AssemblyCompanyAttribute("NHibernate.org")]
[assembly: AssemblyProductAttribute("NHibernate.Caches.Prevalence")]
[assembly: AssemblyCopyrightAttribute("Licensed under LGPL.")]
[assembly: AssemblyVersionAttribute("1.2.1.4000")]
[assembly: AssemblyInformationalVersionAttribute("1.2.1.4000")]
[assembly: AssemblyFileVersionAttribute("1.2.1.4000")]
[assembly: AssemblyKeyFileAttribute("../NHibernate.snk")]
[assembly: AssemblyDelaySignAttribute(false)]

