//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3620
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sconit_CS.SconitWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://com.Sconit.Webservice", ConfigurationName="SconitWS.ClientMgrWSSoap")]
    public interface ClientMgrWSSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://com.Sconit.Webservice/LoadEmployee", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EntityBase))]
        Sconit_CS.SconitWS.Employee LoadEmployee(string employeeCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://com.Sconit.Webservice/ScanBarcode", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EntityBase))]
        Sconit_CS.SconitWS.Resolver ScanBarcode(Sconit_CS.SconitWS.Resolver resolver);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://com.Sconit.Webservice/LoadUser", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EntityBase))]
        Sconit_CS.SconitWS.User LoadUser(string userCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://com.Sconit.Webservice/GetUserPermissions", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EntityBase))]
        Permission[] GetUserPermissions(string categoryCode, string userCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://com.Sconit.Webservice/LoadUserPerference", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EntityBase))]
        Sconit_CS.SconitWS.UserPreference LoadUserPerference(string userCode, string preCode);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://com.Sconit.Webservice")]
    public partial class Employee : EmployeeBase {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Employee))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://com.Sconit.Webservice")]
    public abstract partial class EmployeeBase : EntityBase {
        
        private string codeField;
        
        private string nameField;
        
        private string genderField;
        
        private string departmentField;
        
        private string workGroupField;
        
        private string postField;
        
        private string memoField;
        
        private bool isActiveField;
        
        private System.DateTime lastModifyDateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("Code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Gender {
            get {
                return this.genderField;
            }
            set {
                this.genderField = value;
                this.RaisePropertyChanged("Gender");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Department {
            get {
                return this.departmentField;
            }
            set {
                this.departmentField = value;
                this.RaisePropertyChanged("Department");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string WorkGroup {
            get {
                return this.workGroupField;
            }
            set {
                this.workGroupField = value;
                this.RaisePropertyChanged("WorkGroup");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Post {
            get {
                return this.postField;
            }
            set {
                this.postField = value;
                this.RaisePropertyChanged("Post");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Memo {
            get {
                return this.memoField;
            }
            set {
                this.memoField = value;
                this.RaisePropertyChanged("Memo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public bool IsActive {
            get {
                return this.isActiveField;
            }
            set {
                this.isActiveField = value;
                this.RaisePropertyChanged("IsActive");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public System.DateTime LastModifyDate {
            get {
                return this.lastModifyDateField;
            }
            set {
                this.lastModifyDateField = value;
                this.RaisePropertyChanged("LastModifyDate");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(UserPreferenceBase))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(UserPreference))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PermissionBase))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Permission))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(UserBase))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(User))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ReceiptNote))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TransformerDetail))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Transformer))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Resolver))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(EmployeeBase))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Employee))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://com.Sconit.Webservice")]
    public abstract partial class EntityBase : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(UserPreference))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://com.Sconit.Webservice")]
    public abstract partial class UserPreferenceBase : EntityBase {
        
        private string codeField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("Code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://com.Sconit.Webservice")]
    public partial class UserPreference : UserPreferenceBase {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Permission))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://com.Sconit.Webservice")]
    public abstract partial class PermissionBase : EntityBase {
        
        private int idField;
        
        private string codeField;
        
        private string descriptionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("Code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("Description");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://com.Sconit.Webservice")]
    public partial class Permission : PermissionBase {
        
        private bool statusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("Status");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(User))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://com.Sconit.Webservice")]
    public abstract partial class UserBase : EntityBase {
        
        private string codeField;
        
        private string passwordField;
        
        private string firstNameField;
        
        private string lastNameField;
        
        private string emailField;
        
        private string addressField;
        
        private string genderField;
        
        private string phoneField;
        
        private string mobliePhoneField;
        
        private bool isActiveField;
        
        private System.DateTime lastModifyDateField;
        
        private bool modifyPwdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("Code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("Password");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string FirstName {
            get {
                return this.firstNameField;
            }
            set {
                this.firstNameField = value;
                this.RaisePropertyChanged("FirstName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string LastName {
            get {
                return this.lastNameField;
            }
            set {
                this.lastNameField = value;
                this.RaisePropertyChanged("LastName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
                this.RaisePropertyChanged("Email");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
                this.RaisePropertyChanged("Address");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Gender {
            get {
                return this.genderField;
            }
            set {
                this.genderField = value;
                this.RaisePropertyChanged("Gender");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string Phone {
            get {
                return this.phoneField;
            }
            set {
                this.phoneField = value;
                this.RaisePropertyChanged("Phone");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string MobliePhone {
            get {
                return this.mobliePhoneField;
            }
            set {
                this.mobliePhoneField = value;
                this.RaisePropertyChanged("MobliePhone");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public bool IsActive {
            get {
                return this.isActiveField;
            }
            set {
                this.isActiveField = value;
                this.RaisePropertyChanged("IsActive");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public System.DateTime LastModifyDate {
            get {
                return this.lastModifyDateField;
            }
            set {
                this.lastModifyDateField = value;
                this.RaisePropertyChanged("LastModifyDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public bool ModifyPwd {
            get {
                return this.modifyPwdField;
            }
            set {
                this.modifyPwdField = value;
                this.RaisePropertyChanged("ModifyPwd");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://com.Sconit.Webservice")]
    public partial class User : UserBase {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://com.Sconit.Webservice")]
    public partial class ReceiptNote : EntityBase {
        
        private int sequenceField;
        
        private string receiptNoField;
        
        private string ipNoField;
        
        private string orderNoField;
        
        private string partyFromField;
        
        private string partyToField;
        
        private string dockField;
        
        private System.DateTime createDateField;
        
        private string createUserField;
        
        private string huIdField;
        
        private string itemDescriptionField;
        
        private decimal unitCountField;
        
        private decimal qtyField;
        
        private string statusField;
        
        private string printUrlField;
        
        private string itemCodeField;
        
        private string uomCodeField;
        
        private string lotNoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int Sequence {
            get {
                return this.sequenceField;
            }
            set {
                this.sequenceField = value;
                this.RaisePropertyChanged("Sequence");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ReceiptNo {
            get {
                return this.receiptNoField;
            }
            set {
                this.receiptNoField = value;
                this.RaisePropertyChanged("ReceiptNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string IpNo {
            get {
                return this.ipNoField;
            }
            set {
                this.ipNoField = value;
                this.RaisePropertyChanged("IpNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string OrderNo {
            get {
                return this.orderNoField;
            }
            set {
                this.orderNoField = value;
                this.RaisePropertyChanged("OrderNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string PartyFrom {
            get {
                return this.partyFromField;
            }
            set {
                this.partyFromField = value;
                this.RaisePropertyChanged("PartyFrom");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string PartyTo {
            get {
                return this.partyToField;
            }
            set {
                this.partyToField = value;
                this.RaisePropertyChanged("PartyTo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Dock {
            get {
                return this.dockField;
            }
            set {
                this.dockField = value;
                this.RaisePropertyChanged("Dock");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public System.DateTime CreateDate {
            get {
                return this.createDateField;
            }
            set {
                this.createDateField = value;
                this.RaisePropertyChanged("CreateDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string CreateUser {
            get {
                return this.createUserField;
            }
            set {
                this.createUserField = value;
                this.RaisePropertyChanged("CreateUser");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string HuId {
            get {
                return this.huIdField;
            }
            set {
                this.huIdField = value;
                this.RaisePropertyChanged("HuId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string ItemDescription {
            get {
                return this.itemDescriptionField;
            }
            set {
                this.itemDescriptionField = value;
                this.RaisePropertyChanged("ItemDescription");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public decimal UnitCount {
            get {
                return this.unitCountField;
            }
            set {
                this.unitCountField = value;
                this.RaisePropertyChanged("UnitCount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public decimal Qty {
            get {
                return this.qtyField;
            }
            set {
                this.qtyField = value;
                this.RaisePropertyChanged("Qty");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("Status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string PrintUrl {
            get {
                return this.printUrlField;
            }
            set {
                this.printUrlField = value;
                this.RaisePropertyChanged("PrintUrl");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string ItemCode {
            get {
                return this.itemCodeField;
            }
            set {
                this.itemCodeField = value;
                this.RaisePropertyChanged("ItemCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string UomCode {
            get {
                return this.uomCodeField;
            }
            set {
                this.uomCodeField = value;
                this.RaisePropertyChanged("UomCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public string LotNo {
            get {
                return this.lotNoField;
            }
            set {
                this.lotNoField = value;
                this.RaisePropertyChanged("LotNo");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://com.Sconit.Webservice")]
    public partial class TransformerDetail : EntityBase {
        
        private int idField;
        
        private int sequenceField;
        
        private string huIdField;
        
        private string itemCodeField;
        
        private string itemDescriptionField;
        
        private string uomCodeField;
        
        private decimal unitCountField;
        
        private string lotNoField;
        
        private string storageBinCodeField;
        
        private string statusField;
        
        private string locationCodeField;
        
        private int locationLotDetIdField;
        
        private int orderLocTransIdField;
        
        private string iOTypeField;
        
        private string positionField;
        
        private string manufactureDateField;
        
        private decimal qtyField;
        
        private decimal currentQtyField;
        
        private decimal currentRejectQtyField;
        
        private string sortLevel1Field;
        
        private string colorLevel1Field;
        
        private string sortLevel2Field;
        
        private string colorLevel2Field;
        
        private string s1Field;
        
        private string s2Field;
        
        private string s3Field;
        
        private string s4Field;
        
        private string s5Field;
        
        private System.Nullable<decimal> d1Field;
        
        private System.Nullable<decimal> d2Field;
        
        private System.Nullable<decimal> d3Field;
        
        private System.Nullable<decimal> d4Field;
        
        private System.Nullable<int> iField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int Sequence {
            get {
                return this.sequenceField;
            }
            set {
                this.sequenceField = value;
                this.RaisePropertyChanged("Sequence");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string HuId {
            get {
                return this.huIdField;
            }
            set {
                this.huIdField = value;
                this.RaisePropertyChanged("HuId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string ItemCode {
            get {
                return this.itemCodeField;
            }
            set {
                this.itemCodeField = value;
                this.RaisePropertyChanged("ItemCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string ItemDescription {
            get {
                return this.itemDescriptionField;
            }
            set {
                this.itemDescriptionField = value;
                this.RaisePropertyChanged("ItemDescription");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string UomCode {
            get {
                return this.uomCodeField;
            }
            set {
                this.uomCodeField = value;
                this.RaisePropertyChanged("UomCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public decimal UnitCount {
            get {
                return this.unitCountField;
            }
            set {
                this.unitCountField = value;
                this.RaisePropertyChanged("UnitCount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string LotNo {
            get {
                return this.lotNoField;
            }
            set {
                this.lotNoField = value;
                this.RaisePropertyChanged("LotNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string StorageBinCode {
            get {
                return this.storageBinCodeField;
            }
            set {
                this.storageBinCodeField = value;
                this.RaisePropertyChanged("StorageBinCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("Status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string LocationCode {
            get {
                return this.locationCodeField;
            }
            set {
                this.locationCodeField = value;
                this.RaisePropertyChanged("LocationCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public int LocationLotDetId {
            get {
                return this.locationLotDetIdField;
            }
            set {
                this.locationLotDetIdField = value;
                this.RaisePropertyChanged("LocationLotDetId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public int OrderLocTransId {
            get {
                return this.orderLocTransIdField;
            }
            set {
                this.orderLocTransIdField = value;
                this.RaisePropertyChanged("OrderLocTransId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string IOType {
            get {
                return this.iOTypeField;
            }
            set {
                this.iOTypeField = value;
                this.RaisePropertyChanged("IOType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string Position {
            get {
                return this.positionField;
            }
            set {
                this.positionField = value;
                this.RaisePropertyChanged("Position");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string ManufactureDate {
            get {
                return this.manufactureDateField;
            }
            set {
                this.manufactureDateField = value;
                this.RaisePropertyChanged("ManufactureDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public decimal Qty {
            get {
                return this.qtyField;
            }
            set {
                this.qtyField = value;
                this.RaisePropertyChanged("Qty");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public decimal CurrentQty {
            get {
                return this.currentQtyField;
            }
            set {
                this.currentQtyField = value;
                this.RaisePropertyChanged("CurrentQty");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public decimal CurrentRejectQty {
            get {
                return this.currentRejectQtyField;
            }
            set {
                this.currentRejectQtyField = value;
                this.RaisePropertyChanged("CurrentRejectQty");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public string SortLevel1 {
            get {
                return this.sortLevel1Field;
            }
            set {
                this.sortLevel1Field = value;
                this.RaisePropertyChanged("SortLevel1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public string ColorLevel1 {
            get {
                return this.colorLevel1Field;
            }
            set {
                this.colorLevel1Field = value;
                this.RaisePropertyChanged("ColorLevel1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public string SortLevel2 {
            get {
                return this.sortLevel2Field;
            }
            set {
                this.sortLevel2Field = value;
                this.RaisePropertyChanged("SortLevel2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=22)]
        public string ColorLevel2 {
            get {
                return this.colorLevel2Field;
            }
            set {
                this.colorLevel2Field = value;
                this.RaisePropertyChanged("ColorLevel2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=23)]
        public string s1 {
            get {
                return this.s1Field;
            }
            set {
                this.s1Field = value;
                this.RaisePropertyChanged("s1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=24)]
        public string s2 {
            get {
                return this.s2Field;
            }
            set {
                this.s2Field = value;
                this.RaisePropertyChanged("s2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=25)]
        public string s3 {
            get {
                return this.s3Field;
            }
            set {
                this.s3Field = value;
                this.RaisePropertyChanged("s3");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=26)]
        public string s4 {
            get {
                return this.s4Field;
            }
            set {
                this.s4Field = value;
                this.RaisePropertyChanged("s4");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=27)]
        public string s5 {
            get {
                return this.s5Field;
            }
            set {
                this.s5Field = value;
                this.RaisePropertyChanged("s5");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=28)]
        public System.Nullable<decimal> d1 {
            get {
                return this.d1Field;
            }
            set {
                this.d1Field = value;
                this.RaisePropertyChanged("d1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=29)]
        public System.Nullable<decimal> d2 {
            get {
                return this.d2Field;
            }
            set {
                this.d2Field = value;
                this.RaisePropertyChanged("d2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=30)]
        public System.Nullable<decimal> d3 {
            get {
                return this.d3Field;
            }
            set {
                this.d3Field = value;
                this.RaisePropertyChanged("d3");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=31)]
        public System.Nullable<decimal> d4 {
            get {
                return this.d4Field;
            }
            set {
                this.d4Field = value;
                this.RaisePropertyChanged("d4");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=32)]
        public System.Nullable<int> i {
            get {
                return this.iField;
            }
            set {
                this.iField = value;
                this.RaisePropertyChanged("i");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://com.Sconit.Webservice")]
    public partial class Transformer : EntityBase {
        
        private int idField;
        
        private int orderLocTransIdField;
        
        private string orderNoField;
        
        private int sequenceField;
        
        private string itemCodeField;
        
        private string itemDescriptionField;
        
        private string referenceItemCodeField;
        
        private string uomCodeField;
        
        private decimal unitCountField;
        
        private string locationFromCodeField;
        
        private string locationToCodeField;
        
        private string storageBinCodeField;
        
        private string lotNoField;
        
        private decimal orderedQtyField;
        
        private decimal shippedQtyField;
        
        private decimal receivedQtyField;
        
        private int locationLotDetIdField;
        
        private string oddShipOptionField;
        
        private string locationCodeField;
        
        private decimal qtyField;
        
        private decimal currentQtyField;
        
        private decimal currentRejectQtyField;
        
        private decimal scrapQtyField;
        
        private decimal rejectedQtyField;
        
        private int cartonsField;
        
        private int operationField;
        
        private decimal adjustQtyField;
        
        private TransformerDetail[] transformerDetailsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int OrderLocTransId {
            get {
                return this.orderLocTransIdField;
            }
            set {
                this.orderLocTransIdField = value;
                this.RaisePropertyChanged("OrderLocTransId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string OrderNo {
            get {
                return this.orderNoField;
            }
            set {
                this.orderNoField = value;
                this.RaisePropertyChanged("OrderNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int Sequence {
            get {
                return this.sequenceField;
            }
            set {
                this.sequenceField = value;
                this.RaisePropertyChanged("Sequence");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string ItemCode {
            get {
                return this.itemCodeField;
            }
            set {
                this.itemCodeField = value;
                this.RaisePropertyChanged("ItemCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string ItemDescription {
            get {
                return this.itemDescriptionField;
            }
            set {
                this.itemDescriptionField = value;
                this.RaisePropertyChanged("ItemDescription");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string ReferenceItemCode {
            get {
                return this.referenceItemCodeField;
            }
            set {
                this.referenceItemCodeField = value;
                this.RaisePropertyChanged("ReferenceItemCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string UomCode {
            get {
                return this.uomCodeField;
            }
            set {
                this.uomCodeField = value;
                this.RaisePropertyChanged("UomCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public decimal UnitCount {
            get {
                return this.unitCountField;
            }
            set {
                this.unitCountField = value;
                this.RaisePropertyChanged("UnitCount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string LocationFromCode {
            get {
                return this.locationFromCodeField;
            }
            set {
                this.locationFromCodeField = value;
                this.RaisePropertyChanged("LocationFromCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string LocationToCode {
            get {
                return this.locationToCodeField;
            }
            set {
                this.locationToCodeField = value;
                this.RaisePropertyChanged("LocationToCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string StorageBinCode {
            get {
                return this.storageBinCodeField;
            }
            set {
                this.storageBinCodeField = value;
                this.RaisePropertyChanged("StorageBinCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string LotNo {
            get {
                return this.lotNoField;
            }
            set {
                this.lotNoField = value;
                this.RaisePropertyChanged("LotNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public decimal OrderedQty {
            get {
                return this.orderedQtyField;
            }
            set {
                this.orderedQtyField = value;
                this.RaisePropertyChanged("OrderedQty");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public decimal ShippedQty {
            get {
                return this.shippedQtyField;
            }
            set {
                this.shippedQtyField = value;
                this.RaisePropertyChanged("ShippedQty");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public decimal ReceivedQty {
            get {
                return this.receivedQtyField;
            }
            set {
                this.receivedQtyField = value;
                this.RaisePropertyChanged("ReceivedQty");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public int LocationLotDetId {
            get {
                return this.locationLotDetIdField;
            }
            set {
                this.locationLotDetIdField = value;
                this.RaisePropertyChanged("LocationLotDetId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public string OddShipOption {
            get {
                return this.oddShipOptionField;
            }
            set {
                this.oddShipOptionField = value;
                this.RaisePropertyChanged("OddShipOption");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public string LocationCode {
            get {
                return this.locationCodeField;
            }
            set {
                this.locationCodeField = value;
                this.RaisePropertyChanged("LocationCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public decimal Qty {
            get {
                return this.qtyField;
            }
            set {
                this.qtyField = value;
                this.RaisePropertyChanged("Qty");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public decimal CurrentQty {
            get {
                return this.currentQtyField;
            }
            set {
                this.currentQtyField = value;
                this.RaisePropertyChanged("CurrentQty");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public decimal CurrentRejectQty {
            get {
                return this.currentRejectQtyField;
            }
            set {
                this.currentRejectQtyField = value;
                this.RaisePropertyChanged("CurrentRejectQty");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=22)]
        public decimal ScrapQty {
            get {
                return this.scrapQtyField;
            }
            set {
                this.scrapQtyField = value;
                this.RaisePropertyChanged("ScrapQty");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=23)]
        public decimal RejectedQty {
            get {
                return this.rejectedQtyField;
            }
            set {
                this.rejectedQtyField = value;
                this.RaisePropertyChanged("RejectedQty");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=24)]
        public int Cartons {
            get {
                return this.cartonsField;
            }
            set {
                this.cartonsField = value;
                this.RaisePropertyChanged("Cartons");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=25)]
        public int Operation {
            get {
                return this.operationField;
            }
            set {
                this.operationField = value;
                this.RaisePropertyChanged("Operation");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=26)]
        public decimal AdjustQty {
            get {
                return this.adjustQtyField;
            }
            set {
                this.adjustQtyField = value;
                this.RaisePropertyChanged("AdjustQty");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=27)]
        public TransformerDetail[] TransformerDetails {
            get {
                return this.transformerDetailsField;
            }
            set {
                this.transformerDetailsField = value;
                this.RaisePropertyChanged("TransformerDetails");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://com.Sconit.Webservice")]
    public partial class Resolver : EntityBase {
        
        private string moduleTypeField;
        
        private string userCodeField;
        
        private string codePrefixField;
        
        private string barcodeHeadField;
        
        private string codeField;
        
        private string descriptionField;
        
        private string statusField;
        
        private string pickByField;
        
        private string inputField;
        
        private string binCodeField;
        
        private bool isOddCreateHuField;
        
        private bool isScanHuField;
        
        private bool needPrintAsnField;
        
        private bool needPrintReceiptField;
        
        private bool needInspectionField;
        
        private bool autoPrintHuField;
        
        private bool allowExceedField;
        
        private bool allowCreateDetailField;
        
        private bool isPickFromBinField;
        
        private string iOTypeField;
        
        private string commandField;
        
        private string resultField;
        
        private string orderTypeField;
        
        private string printUrlField;
        
        private string externalOrderNoField;
        
        private string locationCodeField;
        
        private string locationFormCodeField;
        
        private string locationToCodeField;
        
        private Transformer[] transformersField;
        
        private ReceiptNote[] receiptNotesField;
        
        private string[][] workingHoursField;
        
        private string flowCodeField;
        
        private string flowFacilityField;
        
        private string orderNoField;
        
        private string[] sField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ModuleType {
            get {
                return this.moduleTypeField;
            }
            set {
                this.moduleTypeField = value;
                this.RaisePropertyChanged("ModuleType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string UserCode {
            get {
                return this.userCodeField;
            }
            set {
                this.userCodeField = value;
                this.RaisePropertyChanged("UserCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string CodePrefix {
            get {
                return this.codePrefixField;
            }
            set {
                this.codePrefixField = value;
                this.RaisePropertyChanged("CodePrefix");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string BarcodeHead {
            get {
                return this.barcodeHeadField;
            }
            set {
                this.barcodeHeadField = value;
                this.RaisePropertyChanged("BarcodeHead");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("Code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("Description");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("Status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string PickBy {
            get {
                return this.pickByField;
            }
            set {
                this.pickByField = value;
                this.RaisePropertyChanged("PickBy");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string Input {
            get {
                return this.inputField;
            }
            set {
                this.inputField = value;
                this.RaisePropertyChanged("Input");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string BinCode {
            get {
                return this.binCodeField;
            }
            set {
                this.binCodeField = value;
                this.RaisePropertyChanged("BinCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public bool IsOddCreateHu {
            get {
                return this.isOddCreateHuField;
            }
            set {
                this.isOddCreateHuField = value;
                this.RaisePropertyChanged("IsOddCreateHu");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public bool IsScanHu {
            get {
                return this.isScanHuField;
            }
            set {
                this.isScanHuField = value;
                this.RaisePropertyChanged("IsScanHu");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public bool NeedPrintAsn {
            get {
                return this.needPrintAsnField;
            }
            set {
                this.needPrintAsnField = value;
                this.RaisePropertyChanged("NeedPrintAsn");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public bool NeedPrintReceipt {
            get {
                return this.needPrintReceiptField;
            }
            set {
                this.needPrintReceiptField = value;
                this.RaisePropertyChanged("NeedPrintReceipt");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public bool NeedInspection {
            get {
                return this.needInspectionField;
            }
            set {
                this.needInspectionField = value;
                this.RaisePropertyChanged("NeedInspection");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public bool AutoPrintHu {
            get {
                return this.autoPrintHuField;
            }
            set {
                this.autoPrintHuField = value;
                this.RaisePropertyChanged("AutoPrintHu");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public bool AllowExceed {
            get {
                return this.allowExceedField;
            }
            set {
                this.allowExceedField = value;
                this.RaisePropertyChanged("AllowExceed");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public bool AllowCreateDetail {
            get {
                return this.allowCreateDetailField;
            }
            set {
                this.allowCreateDetailField = value;
                this.RaisePropertyChanged("AllowCreateDetail");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public bool IsPickFromBin {
            get {
                return this.isPickFromBinField;
            }
            set {
                this.isPickFromBinField = value;
                this.RaisePropertyChanged("IsPickFromBin");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public string IOType {
            get {
                return this.iOTypeField;
            }
            set {
                this.iOTypeField = value;
                this.RaisePropertyChanged("IOType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public string Command {
            get {
                return this.commandField;
            }
            set {
                this.commandField = value;
                this.RaisePropertyChanged("Command");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public string Result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
                this.RaisePropertyChanged("Result");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=22)]
        public string OrderType {
            get {
                return this.orderTypeField;
            }
            set {
                this.orderTypeField = value;
                this.RaisePropertyChanged("OrderType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=23)]
        public string PrintUrl {
            get {
                return this.printUrlField;
            }
            set {
                this.printUrlField = value;
                this.RaisePropertyChanged("PrintUrl");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=24)]
        public string ExternalOrderNo {
            get {
                return this.externalOrderNoField;
            }
            set {
                this.externalOrderNoField = value;
                this.RaisePropertyChanged("ExternalOrderNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=25)]
        public string LocationCode {
            get {
                return this.locationCodeField;
            }
            set {
                this.locationCodeField = value;
                this.RaisePropertyChanged("LocationCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=26)]
        public string LocationFormCode {
            get {
                return this.locationFormCodeField;
            }
            set {
                this.locationFormCodeField = value;
                this.RaisePropertyChanged("LocationFormCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=27)]
        public string LocationToCode {
            get {
                return this.locationToCodeField;
            }
            set {
                this.locationToCodeField = value;
                this.RaisePropertyChanged("LocationToCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=28)]
        public Transformer[] Transformers {
            get {
                return this.transformersField;
            }
            set {
                this.transformersField = value;
                this.RaisePropertyChanged("Transformers");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=29)]
        public ReceiptNote[] ReceiptNotes {
            get {
                return this.receiptNotesField;
            }
            set {
                this.receiptNotesField = value;
                this.RaisePropertyChanged("ReceiptNotes");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=30)]
        [System.Xml.Serialization.XmlArrayItemAttribute("ArrayOfString")]
        [System.Xml.Serialization.XmlArrayItemAttribute(NestingLevel=1)]
        public string[][] WorkingHours {
            get {
                return this.workingHoursField;
            }
            set {
                this.workingHoursField = value;
                this.RaisePropertyChanged("WorkingHours");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=31)]
        public string FlowCode {
            get {
                return this.flowCodeField;
            }
            set {
                this.flowCodeField = value;
                this.RaisePropertyChanged("FlowCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=32)]
        public string FlowFacility {
            get {
                return this.flowFacilityField;
            }
            set {
                this.flowFacilityField = value;
                this.RaisePropertyChanged("FlowFacility");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=33)]
        public string OrderNo {
            get {
                return this.orderNoField;
            }
            set {
                this.orderNoField = value;
                this.RaisePropertyChanged("OrderNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=34)]
        public string[] s {
            get {
                return this.sField;
            }
            set {
                this.sField = value;
                this.RaisePropertyChanged("s");
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface ClientMgrWSSoapChannel : Sconit_CS.SconitWS.ClientMgrWSSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class ClientMgrWSSoapClient : System.ServiceModel.ClientBase<Sconit_CS.SconitWS.ClientMgrWSSoap>, Sconit_CS.SconitWS.ClientMgrWSSoap {
        
        public ClientMgrWSSoapClient() {
        }
        
        public ClientMgrWSSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ClientMgrWSSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ClientMgrWSSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ClientMgrWSSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Sconit_CS.SconitWS.Employee LoadEmployee(string employeeCode) {
            return base.Channel.LoadEmployee(employeeCode);
        }
        
        public Sconit_CS.SconitWS.Resolver ScanBarcode(Sconit_CS.SconitWS.Resolver resolver) {
            return base.Channel.ScanBarcode(resolver);
        }
        
        public Sconit_CS.SconitWS.User LoadUser(string userCode) {
            return base.Channel.LoadUser(userCode);
        }
        
        public Permission[] GetUserPermissions(string categoryCode, string userCode) {
            return base.Channel.GetUserPermissions(categoryCode, userCode);
        }
        
        public Sconit_CS.SconitWS.UserPreference LoadUserPerference(string userCode, string preCode) {
            return base.Channel.LoadUserPerference(userCode, preCode);
        }
    }
}
